LikeLion12th-OMEB/Backend

- src/main/java/com/example/OMEB/global/aop/AssignUserId.java
- src/main/java/com/example/OMEB/global/aop/UserIdInjectionAspect.java
- src/main/java/com/example/OMEB/global/base/domain/BaseEntity.java
- src/main/java/com/example/OMEB/global/base/dto/FailedResponseBody.java
- src/main/java/com/example/OMEB/global/base/dto/ResponseBody.java
- src/main/java/com/example/OMEB/global/base/dto/SuccessResponseBody.java
- src/main/java/com/example/OMEB/global/base/exception/ErrorCode.java
- src/main/java/com/example/OMEB/global/base/exception/GlobalExceptionHandler.java
- src/main/java/com/example/OMEB/global/base/exception/ServiceException.java
> 프로젝트 기초 세팅

- src/main/java/com/example/OMEB/domain/book/persistence/entity/ApplicationBook.java
- src/main/java/com/example/OMEB/domain/book/persistence/entity/Book.java
- src/main/java/com/example/OMEB/domain/book/persistence/entity/Tag.java
- src/main/java/com/example/OMEB/domain/review/persistence/entity/Like.java
- src/main/java/com/example/OMEB/domain/review/persistence/entity/Review.java
- src/main/java/com/example/OMEB/domain/user/persistence/entity/BookMark.java
- src/main/java/com/example/OMEB/domain/user/persistence/entity/ExpLog.java
- src/main/java/com/example/OMEB/domain/user/persistence/entity/History.java
- src/main/java/com/example/OMEB/domain/user/persistence/entity/Profile.java
- src/main/java/com/example/OMEB/domain/user/persistence/entity/User.java
- src/main/java/com/example/OMEB/global/oauth/user/OAuth2Provider.java
> [init] 테이블 엔티티 추가

- .github/workflows/CI.yml
- src/main/java/com/example/OMEB/domain/book/persistence/entity/Book.java
- src/main/java/com/example/OMEB/domain/book/persistence/entity/Tag.java
- src/main/java/com/example/OMEB/domain/book/persistence/repository/BookRepository.java
- src/main/java/com/example/OMEB/domain/book/persistence/repository/TagRepository.java
- src/main/java/com/example/OMEB/domain/review/application/service/ReviewService.java
- src/main/java/com/example/OMEB/domain/review/persistence/entity/Review.java
- src/main/java/com/example/OMEB/domain/review/persistence/repository/ReviewRepository.java
- src/main/java/com/example/OMEB/domain/review/persistence/vo/TagName.java
- src/main/java/com/example/OMEB/domain/review/presentation/controller/ReviewController.java
- src/main/java/com/example/OMEB/domain/review/presentation/dto/request/ReviewCreateRequest.java
- src/main/java/com/example/OMEB/domain/review/presentation/dto/response/ReviewInfoResponse.java
- src/main/java/com/example/OMEB/domain/user/persistence/entity/User.java
- src/main/java/com/example/OMEB/domain/user/persistence/repository/UserRepository.java
- src/main/java/com/example/OMEB/global/base/domain/BaseEntity.java
- src/main/java/com/example/OMEB/global/base/exception/ErrorCode.java
- src/main/java/com/example/OMEB/global/base/exception/GlobalExceptionHandler.java
- reviw 생성 도메인 로직 구현
- 해당 controller repo 구현
- service 위주로 봐주세요
- 수정한 엔티티 참고해주세요
- service 계층에서 영속성 연관관계 매핑 로직을 영속성 엔티티에만 구현할려고 했습니다 이의 없으시면 컨벤션 따라주시면 좋을거 같아요
#13
> [#13] review 생성 기능 구현 및 영속성 엔티티 관련 자잘한 수정

- src/test/java/com/example/OMEB/domain/review/persistence/repository/ReviewRepositoryTest.java
> [refactor] test 코드 수정

- build.gradle
- src/main/java/com/example/OMEB/domain/book/application/service/Book.java
- src/main/java/com/example/OMEB/domain/book/application/service/BookCommandService.java
- src/main/java/com/example/OMEB/domain/book/application/service/BookQueryService.java
- src/main/java/com/example/OMEB/domain/book/application/service/Emotion.java
- src/main/java/com/example/OMEB/domain/book/application/service/NaverBookSearchClient.java
- src/main/java/com/example/OMEB/domain/book/application/usecase/BookUseCase.java
- src/main/java/com/example/OMEB/domain/book/persistence/entity/Book.java
- src/main/java/com/example/OMEB/domain/book/persistence/repository/BookRepository.java
- src/main/java/com/example/OMEB/domain/book/persistence/repository/TagRepository.java
- src/main/java/com/example/OMEB/domain/book/presentation/BookApplicationController.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/NaverBookDTO.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/request/BookApplicationRequest.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/request/BookSearchRequest.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/response/BookInfoResponse.java
- src/main/java/com/example/OMEB/domain/review/application/service/ReviewService.java
- src/main/java/com/example/OMEB/domain/review/persistence/entity/Review.java
- src/main/java/com/example/OMEB/domain/review/persistence/entity/Tag.java
- src/main/java/com/example/OMEB/global/base/exception/ErrorCode.java
- src/main/resources/application.yml
- src/test/java/com/example/OMEB/domain/review/persistence/NaverClientTest.java
- src/test/java/com/example/OMEB/domain/review/persistence/repository/ReviewRepositoryTest.java
- naver open api client 구현
- 테스트 코드로 통신 확인
- key 관련 보안 설정 추가 
- webflux 의존성 추가
- book 등록 및 검색 로직 구현
- 책 데이터 추가 로직
- book Service controller repo 위주로
#17
> [#17] webclient 의존성 추가 및 naver open api client 구현

- src/main/java/com/example/OMEB/domain/book/application/service/NaverBookSearchClient.java
- src/test/java/com/example/OMEB/domain/review/persistence/NaverClientTest.java
- src/test/java/com/example/OMEB/domain/review/persistence/repository/ReviewRepositoryTest.java
> test 에러 해결

- src/main/java/com/example/OMEB/domain/user/persistence/entity/User.java
> [refactor] : 오류 수정

- build.gradle
- src/main/java/com/example/OMEB/domain/book/application/usecase/BookUseCase.java
- src/main/java/com/example/OMEB/domain/book/presentation/BookApplicationController.java
- src/main/java/com/example/OMEB/domain/book/presentation/BookMarkController.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/request/BookApplicationRequest.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/request/BookSearchRequest.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/response/BookInfoResponse.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/response/BookTitleInfoResponse.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/response/BookTitleListResponse.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/response/NaverBookListResponse.java
- src/main/java/com/example/OMEB/domain/profile/application/service/S3PresignedUrlService.java
- src/main/java/com/example/OMEB/domain/profile/application/usecase/ProfileUseCase.java
- src/main/java/com/example/OMEB/domain/profile/presentaion/ProfileController.java
- src/main/java/com/example/OMEB/domain/profile/presentaion/dto/PresignedUrlResponse.java
- src/main/java/com/example/OMEB/domain/review/application/service/ReviewService.java
- src/main/java/com/example/OMEB/domain/review/presentation/controller/ReviewController.java
- src/main/java/com/example/OMEB/domain/review/presentation/dto/request/ReviewCreateRequest.java
- src/main/java/com/example/OMEB/domain/review/presentation/dto/request/ReviewUpdateRequest.java
- src/main/java/com/example/OMEB/domain/review/presentation/dto/response/ReviewInfoResponse.java
- src/main/java/com/example/OMEB/domain/review/presentation/dto/response/ReviewPageResponse.java
- src/main/java/com/example/OMEB/global/base/exception/ErrorCode.java
- src/main/java/com/example/OMEB/global/config/SwaggerConfig.java
- src/main/resources/application.yml
- swagger 설정 파일 추가 
- controller 에 swagger 적용
- dto 에 swagger 적용
- swagger  설정과 controller , dto 위주로 봐주세요
- 자세한 컨벤션은 노션을 통해 공유할 예정
resolves #이슈번호
> Swagger 적용

- src/main/java/com/example/OMEB/domain/user/persistence/entity/User.java
- src/main/java/com/example/OMEB/domain/user/persistence/repository/UserRepository.java
- src/main/java/com/example/OMEB/global/config/RedisConfig.java
- src/main/java/com/example/OMEB/global/jwt/JwtFilter.java
- src/main/java/com/example/OMEB/global/jwt/JwtUtils.java
- src/main/java/com/example/OMEB/global/jwt/refreshToken/RefreshToken.java
- src/main/java/com/example/OMEB/global/jwt/refreshToken/RefreshTokenRepository.java
- src/main/java/com/example/OMEB/global/oauth/handler/OAuth2AuthenticationSuccessHandler.java
- filter 오류 및 회원가입 로직 수정
resolves #이슈번호
> [refactor] 오류 해결 및 회원가입 로직 수정

- src/main/java/com/example/OMEB/domain/book/api/BookApplicationControllerApi.java
- src/main/java/com/example/OMEB/domain/book/api/BookInfoControllerApi.java
- src/main/java/com/example/OMEB/domain/book/api/BookMarkControllerApi.java
- src/main/java/com/example/OMEB/domain/book/presentation/controller/BookApplicationController.java
- src/main/java/com/example/OMEB/domain/book/presentation/controller/BookInfoController.java
- src/main/java/com/example/OMEB/domain/book/presentation/controller/BookMarkController.java
- src/main/java/com/example/OMEB/domain/profile/api/ProfileControllerApi.java
- src/main/java/com/example/OMEB/domain/profile/presentaion/ProfileController.java
- src/main/java/com/example/OMEB/domain/review/api/ReviewControllerApi.java
- src/main/java/com/example/OMEB/domain/review/presentation/controller/ReviewController.java
- src/main/java/com/example/OMEB/global/aop/UserPrincipal.java
- Swagger 리팩터링 
- UserPrincipal 커스텀 및 관련 리팩터링
- Controller 설계 방식 한번 봐주세요
resolves #이슈번호
> swagger 리팩터링 및 UserPrincipal 커스텀

- .github/workflows/CICD.yml
- src/main/java/com/example/OMEB/domain/auth/application/service/AuthService.java
- src/main/java/com/example/OMEB/domain/auth/presentation/controller/AuthController.java
- src/main/java/com/example/OMEB/domain/auth/presentation/dto/request/TokenRequest.java
- src/main/java/com/example/OMEB/domain/auth/presentation/dto/response/SignUpResponse.java
- src/main/java/com/example/OMEB/domain/auth/presentation/dto/response/TokenResponse.java
- src/main/java/com/example/OMEB/domain/user/persistence/entity/User.java
- src/main/java/com/example/OMEB/global/base/exception/ErrorCode.java
- CD 오류 해결
- 회원가입, 로그아웃, 토큰 재발급 구현
resolves #이슈번호
> [refactor] 기능 구현 및 CD 오류 해결

- src/main/java/com/example/OMEB/domain/book/application/service/BookQueryService.java
- src/main/java/com/example/OMEB/domain/book/application/usecase/BookUseCase.java
- src/main/java/com/example/OMEB/domain/book/presentation/controller/BookInfoController.java
- Book 상세조회 api 오류 개선
userPrincipal 에 null 이 들어간다는 점을 관과 함
> [refactor] : 프론트에서 요구하는 에러 찾아서 수정함

- src/main/java/com/example/OMEB/domain/auth/presentation/api/AuthControllerAPI.java
- src/main/java/com/example/OMEB/domain/auth/presentation/controller/AuthController.java
- src/main/java/com/example/OMEB/domain/auth/presentation/dto/request/LogoutRequest.java
- src/main/java/com/example/OMEB/domain/auth/presentation/dto/request/SignUpRequest.java
- src/main/java/com/example/OMEB/domain/auth/presentation/dto/response/SignUpResponse.java
- src/main/java/com/example/OMEB/domain/auth/presentation/dto/response/TokenResponse.java
- src/main/java/com/example/OMEB/global/config/SecurityConfig.java
> Auth Api Swagger 적용 및 CORS 설정추가

- src/main/java/com/example/OMEB/domain/book/api/BookInfoControllerApi.java
- src/main/java/com/example/OMEB/domain/book/application/service/BookCommandService.java
- src/main/java/com/example/OMEB/domain/book/application/service/BookQueryService.java
- src/main/java/com/example/OMEB/domain/book/application/usecase/BookUseCase.java
- src/main/java/com/example/OMEB/domain/book/persistence/repository/BookRepository.java
- src/main/java/com/example/OMEB/domain/book/presentation/controller/BookApplicationController.java
- src/main/java/com/example/OMEB/domain/book/presentation/controller/BookInfoController.java
- src/main/java/com/example/OMEB/domain/book/presentation/dto/response/BookTitleInfoResponse.java
- src/main/java/com/example/OMEB/domain/user/persistence/entity/User.java
- src/test/java/com/example/OMEB/domain/book/persistence/repository/BookRepositoryTest.java
- 리뷰 많은 순서 책 10권 조회 api 구현
- user 테이블 이름 수정
- user 예약어라서 테이블 이름 users 로 수정했습니다.
- user 의 기존 데이터 삭제 했습니다
- 리뷰 많은 순서로 책 조회 기능 구현 했고 repository 를 네이티브 쿼리로 (성능 때문에) 구현했습니다
resolves #이슈번호
> book 리뷰 많은 순서로 10권 조회 기능 구현

- settings.gradle
> cicd 오류 수정

- .github/workflows/Batch-CICD.yml
> 기존 cicd 와 batch cicd 수정

- batch/src/main/java/batch/batch/controller/HelloController.java
> test :batch cicd test

- .github/workflows/Batch-CICD.yml
- batch/Dockerfile
> cicd 오류 수정 docker

- batch/Dockerfile
> dockerfile context 기준으로 오류 수정

- .github/workflows/Batch-CICD.yml
- batch/Dockerfile
- batch/build.gradle
- settings.gradle
> gradle 서브 프로젝트 오류 해결

- .github/workflows/Batch-CICD.yml
> Batch-CICD.yml 수정

- batch/src/main/java/batch/batch/rdb/entity/Book.java
> 서브모듈 버전 문제 해결

- Dockerfile
> [docs] ssl 인증서가 컨테이너 내에 존재하도록 수정

- src/main/java/com/example/OMEB/global/config/SecurityConfig.java
- Security 설정에 PATCH 메서드 추가
resolves #이슈번호
>  cors PATCH 메서드 추가

- src/main/java/com/example/OMEB/OmebApplication.java
- src/main/java/com/example/OMEB/domain/auth/application/service/AuthService.java
- src/main/java/com/example/OMEB/domain/user/application/service/UserService.java
- src/main/java/com/example/OMEB/global/utils/CookieUtils.java
- src/main/resources/static/idex.html
> Auth 로직 오류 수정

- build.gradle
- src/main/java/com/example/OMEB/domain/book/persistence/repository/TagRepository.java
- src/main/java/com/example/OMEB/domain/review/api/ReviewControllerApi.java
- src/main/java/com/example/OMEB/domain/review/application/service/ReviewService.java
- src/main/java/com/example/OMEB/domain/review/persistence/repository/ReviewRepository.java
- src/main/java/com/example/OMEB/domain/review/presentation/controller/ReviewController.java
- src/main/java/com/example/OMEB/domain/review/presentation/dto/response/ReviewPageResponse.java
- reivew 생성 오류 해결 ( tagName 으로 찾는 repository String-> Enum 으로 변경)
- review 조회 좋아요 순 조회 기능 추가
- spring ai 관련 build 파일 수정
- review 조회 api 
- tagRepository
resolves #이슈번호
> 프론트 요구사항으로 인한 수정 ( review 오류 , 리뷰 좋아요순 조회 기능 추가) 

- src/main/java/com/example/OMEB/domain/review/persistence/repository/LikeRepository.java
> 좋아요 여부 조회 repository 오류 수정

- src/main/java/com/example/OMEB/domain/book/application/service/BookQueryService.java
- src/main/java/com/example/OMEB/domain/book/persistence/entity/Book.java
- src/main/java/com/example/OMEB/domain/bookmark/api/BookMarkControllerApi.java
- src/main/java/com/example/OMEB/domain/bookmark/application/service/BookMarkServiceImpl.java
- src/main/java/com/example/OMEB/domain/bookmark/persistence/entity/BookMark.java
- src/main/java/com/example/OMEB/domain/bookmark/persistence/repository/BookMarkRepository.java
- src/main/java/com/example/OMEB/domain/bookmark/presentation/controller/BookMarkController.java
- src/main/java/com/example/OMEB/domain/bookmark/presentation/dto/response/BookMarkBookTitleListResponse.java
- src/main/java/com/example/OMEB/domain/review/persistence/repository/ReviewRepository.java
- src/main/java/com/example/OMEB/domain/review/presentation/dto/response/ReviewInfoResponse.java
- src/main/java/com/example/OMEB/domain/user/persistence/entity/User.java
- bookmark 패키지 구조 리팩터링
- review 조회 response 에 유저 image url 추가
- bookmark 구조
- review dto
resolves #이슈번호
> 프론트 요청 사항으로 인한 수정( 리뷰 조회시 유저 프로필 이미지 추가 ) 및 패키지 구조 리팩터링

- src/main/java/com/example/OMEB/domain/bookmark/application/service/BookMarkServiceImpl.java
- src/main/java/com/example/OMEB/domain/review/application/service/ReviewService.java
> [refactor] 리뷰 수정 및 북마크 오류 해결

- src/main/java/com/example/OMEB/domain/user/application/service/UserService.java
- src/main/java/com/example/OMEB/domain/user/persistence/entity/History.java
- src/main/java/com/example/OMEB/domain/user/persistence/repository/HistoryRepository.java
- src/main/java/com/example/OMEB/domain/user/presentation/api/UserApi.java
- src/main/java/com/example/OMEB/domain/user/presentation/controller/UserController.java
- src/main/java/com/example/OMEB/domain/user/presentation/dto/request/HistoryRequest.java
- src/main/java/com/example/OMEB/domain/user/presentation/dto/response/HistoryResponse.java
- src/main/java/com/example/OMEB/domain/user/presentation/dto/response/UserHistoryPageResponse.java
- 히스토리 create, get api 구현
- 서비스 로직 위추로 리뷰해주시면 됩니다.
resolves #이슈번호
> [enh] 히스토리 저장 및 조회 API 구현

- src/main/java/com/example/OMEB/global/config/SecurityConfig.java
> [refactor] 최종 프론트 배포주소 cors 해결

- src/main/java/com/example/OMEB/domain/profile/application/ProfileUrlUtill.java
> 프로필 수정 오류 해결
